### ISSUE TITLE
The `SuccessMessageMixin` is missing

### ISSUE THREAD

**Issue by KommuSoft** [classy-python/ccbv#206] opened 2022-11-17 00:31 UTC
The `messages` framework also exports a `SuccessMessageMixin`, so the inspector will need to collect that one as well:

https://docs.djangoproject.com/en/4.1/ref/contrib/messages/#django.contrib.messages.views.SuccessMessageMixin

**Comment by meshy** [comment] 2022-11-18 09:54
As mentioned in #207, I'm closing this as a duplicate of #121

**Closed by meshy** 2022-11-18 09:54 UTC
